// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package org.bzz.extractor.protobuf



object ExtractorProto {
  private lazy val ProtoBytes: Array[Byte] =
      com.trueaccord.scalapb.Encoding.fromBase64(scala.collection.Seq(
  """Cg9leHRyYWN0b3IucHJvdG8SGm9yZy5ienouZXh0cmFjdG9yLnByb3RvYnVmIjoKEVJlcG9zaXRvcmllc0JhdGNoEiUKDnJlc
  G9zaXRvcnlfaWRzGAEgAygJUg1yZXBvc2l0b3J5SWRzIqoBCghGaWxlVWFzdBIWCgZyZXBvSWQYASABKAlSBnJlcG9JZBIYCgdyZ
  XBvVXJsGAIgASgJUgdyZXBvVXJsEhIKBHBhdGgYAyABKAlSBHBhdGgSEgoEbGFuZxgEIAEoCVIEbGFuZxISCgR1YXN0GAUgASgMU
  gR1YXN0EhwKCXJlZmVyZW5jZRgGIAEoCVIJcmVmZXJlbmNlEhIKBGhhc2gYByABKAxSBGhhc2gygAEKDVVhc3RFeHRyYWN0b3ISb
  woUUGFyc2VFdmVyeUZpbGVUb1Vhc3QSLS5vcmcuYnp6LmV4dHJhY3Rvci5wcm90b2J1Zi5SZXBvc2l0b3JpZXNCYXRjaBokLm9yZ
  y5ienouZXh0cmFjdG9yLnByb3RvYnVmLkZpbGVVYXN0IgAwAUILWglleHRyYWN0b3JiBnByb3RvMw=="""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, Seq(
    ))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, Array(
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}