// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package org.bzz.extractor.protobuf



object ExtractorProto {
  private lazy val ProtoBytes: Array[Byte] =
      com.trueaccord.scalapb.Encoding.fromBase64(scala.collection.Seq(
  """Cg9leHRyYWN0b3IucHJvdG8SGm9yZy5ienouZXh0cmFjdG9yLnByb3RvYnVmIjgKEVJlcG9zaXRvcmllc0JhdGNoEiMKDXJlc
  G9zaXRvcnlfaWQYASADKAlSDHJlcG9zaXRvcnlJZCKqAQoIRmlsZVVhc3QSFgoGcmVwb0lkGAEgASgJUgZyZXBvSWQSGAoHcmVwb
  1VybBgCIAEoCVIHcmVwb1VybBISCgRwYXRoGAMgASgJUgRwYXRoEhIKBGxhbmcYBCABKAlSBGxhbmcSEgoEdWFzdBgFIAEoDFIEd
  WFzdBIcCglyZWZlcmVuY2UYBiABKAlSCXJlZmVyZW5jZRISCgRoYXNoGAcgASgMUgRoYXNoMoABCg1VYXN0RXh0cmFjdG9yEm8KF
  FBhcnNlRXZlcnlGaWxlVG9VYXN0Ei0ub3JnLmJ6ei5leHRyYWN0b3IucHJvdG9idWYuUmVwb3NpdG9yaWVzQmF0Y2gaJC5vcmcuY
  np6LmV4dHJhY3Rvci5wcm90b2J1Zi5GaWxlVWFzdCIAMAFCC1oJZXh0cmFjdG9yYgZwcm90bzM="""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, Seq(
    ))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, Array(
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}