// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package org.bzz.extractor.protobuf



/** Batching to amortize DB load
  */
@SerialVersionUID(0L)
final case class RepositoriesBatch(
    repositoryIds: _root_.scala.collection.Seq[String] = _root_.scala.collection.Seq.empty
    ) extends com.trueaccord.scalapb.GeneratedMessage with com.trueaccord.scalapb.Message[RepositoriesBatch] with com.trueaccord.lenses.Updatable[RepositoriesBatch] {
    @transient
    private[this] var __serializedSizeCachedValue: Int = 0
    private[this] def __computeSerializedValue(): Int = {
      var __size = 0
      repositoryIds.foreach(repositoryIds => __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(1, repositoryIds))
      __size
    }
    final override def serializedSize: Int = {
      var read = __serializedSizeCachedValue
      if (read == 0) {
        read = __computeSerializedValue()
        __serializedSizeCachedValue = read
      }
      read
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): Unit = {
      repositoryIds.foreach { __v =>
        _output__.writeString(1, __v)
      };
    }
    def mergeFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): org.bzz.extractor.protobuf.RepositoriesBatch = {
      val __repositoryIds = (_root_.scala.collection.immutable.Vector.newBuilder[String] ++= this.repositoryIds)
      var _done__ = false
      while (!_done__) {
        val _tag__ = _input__.readTag()
        _tag__ match {
          case 0 => _done__ = true
          case 10 =>
            __repositoryIds += _input__.readString()
          case tag => _input__.skipField(tag)
        }
      }
      org.bzz.extractor.protobuf.RepositoriesBatch(
          repositoryIds = __repositoryIds.result()
      )
    }
    def clearRepositoryIds = copy(repositoryIds = _root_.scala.collection.Seq.empty)
    def addRepositoryIds(__vs: String*): RepositoriesBatch = addAllRepositoryIds(__vs)
    def addAllRepositoryIds(__vs: TraversableOnce[String]): RepositoriesBatch = copy(repositoryIds = repositoryIds ++ __vs)
    def withRepositoryIds(__v: _root_.scala.collection.Seq[String]): RepositoriesBatch = copy(repositoryIds = __v)
    def getFieldByNumber(__fieldNumber: Int): scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => repositoryIds
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PRepeated(repositoryIds.map(_root_.scalapb.descriptors.PString)(_root_.scala.collection.breakOut))
      }
    }
    override def toString: String = _root_.com.trueaccord.scalapb.TextFormat.printToUnicodeString(this)
    def companion = org.bzz.extractor.protobuf.RepositoriesBatch
}

object RepositoriesBatch extends com.trueaccord.scalapb.GeneratedMessageCompanion[org.bzz.extractor.protobuf.RepositoriesBatch] {
  implicit def messageCompanion: com.trueaccord.scalapb.GeneratedMessageCompanion[org.bzz.extractor.protobuf.RepositoriesBatch] = this
  def fromFieldsMap(__fieldsMap: scala.collection.immutable.Map[_root_.com.google.protobuf.Descriptors.FieldDescriptor, scala.Any]): org.bzz.extractor.protobuf.RepositoriesBatch = {
    require(__fieldsMap.keys.forall(_.getContainingType() == javaDescriptor), "FieldDescriptor does not match message type.")
    val __fields = javaDescriptor.getFields
    org.bzz.extractor.protobuf.RepositoriesBatch(
      __fieldsMap.getOrElse(__fields.get(0), Nil).asInstanceOf[_root_.scala.collection.Seq[String]]
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[org.bzz.extractor.protobuf.RepositoriesBatch] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      require(__fieldsMap.keys.forall(_.containingMessage == scalaDescriptor), "FieldDescriptor does not match message type.")
      org.bzz.extractor.protobuf.RepositoriesBatch(
        __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.collection.Seq[String]]).getOrElse(_root_.scala.collection.Seq.empty)
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = ExtractorProto.javaDescriptor.getMessageTypes.get(0)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = ExtractorProto.scalaDescriptor.messages(0)
  def messageCompanionForFieldNumber(__fieldNumber: Int): _root_.com.trueaccord.scalapb.GeneratedMessageCompanion[_] = throw new MatchError(__fieldNumber)
  def enumCompanionForFieldNumber(__fieldNumber: Int): _root_.com.trueaccord.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = org.bzz.extractor.protobuf.RepositoriesBatch(
  )
  implicit class RepositoriesBatchLens[UpperPB](_l: _root_.com.trueaccord.lenses.Lens[UpperPB, org.bzz.extractor.protobuf.RepositoriesBatch]) extends _root_.com.trueaccord.lenses.ObjectLens[UpperPB, org.bzz.extractor.protobuf.RepositoriesBatch](_l) {
    def repositoryIds: _root_.com.trueaccord.lenses.Lens[UpperPB, _root_.scala.collection.Seq[String]] = field(_.repositoryIds)((c_, f_) => c_.copy(repositoryIds = f_))
  }
  final val REPOSITORY_IDS_FIELD_NUMBER = 1
}
