// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf/extractor.proto

/*
Package extractor is a generated protocol buffer package.

It is generated from these files:
	protobuf/extractor.proto

It has these top-level messages:
	RepositoriesBatch
	FileUast
*/
package extractor

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Batching to amortize DB load
type RepositoriesBatch struct {
	RepositoryId []string `protobuf:"bytes,1,rep,name=repository_id,json=repositoryId" json:"repository_id,omitempty"`
}

func (m *RepositoriesBatch) Reset()                    { *m = RepositoriesBatch{} }
func (m *RepositoriesBatch) String() string            { return proto.CompactTextString(m) }
func (*RepositoriesBatch) ProtoMessage()               {}
func (*RepositoriesBatch) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *RepositoriesBatch) GetRepositoryId() []string {
	if m != nil {
		return m.RepositoryId
	}
	return nil
}

type FileUast struct {
	RepoId  string `protobuf:"bytes,1,opt,name=repoId" json:"repoId,omitempty"`
	RepoUrl string `protobuf:"bytes,2,opt,name=repoUrl" json:"repoUrl,omitempty"`
	Path    string `protobuf:"bytes,3,opt,name=path" json:"path,omitempty"`
	Lang    string `protobuf:"bytes,4,opt,name=lang" json:"lang,omitempty"`
	// import "github.com/bblfsh/sdk/uast/generated.proto";
	// github.com.bblfsh.sdk.uast.Node file_uast;
	Uast      []byte `protobuf:"bytes,5,opt,name=uast,proto3" json:"uast,omitempty"`
	Reference string `protobuf:"bytes,6,opt,name=reference" json:"reference,omitempty"`
	Hash      []byte `protobuf:"bytes,7,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (m *FileUast) Reset()                    { *m = FileUast{} }
func (m *FileUast) String() string            { return proto.CompactTextString(m) }
func (*FileUast) ProtoMessage()               {}
func (*FileUast) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *FileUast) GetRepoId() string {
	if m != nil {
		return m.RepoId
	}
	return ""
}

func (m *FileUast) GetRepoUrl() string {
	if m != nil {
		return m.RepoUrl
	}
	return ""
}

func (m *FileUast) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *FileUast) GetLang() string {
	if m != nil {
		return m.Lang
	}
	return ""
}

func (m *FileUast) GetUast() []byte {
	if m != nil {
		return m.Uast
	}
	return nil
}

func (m *FileUast) GetReference() string {
	if m != nil {
		return m.Reference
	}
	return ""
}

func (m *FileUast) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func init() {
	proto.RegisterType((*RepositoriesBatch)(nil), "org.bzz.extractor.protobuf.RepositoriesBatch")
	proto.RegisterType((*FileUast)(nil), "org.bzz.extractor.protobuf.FileUast")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for UastExtractor service

type UastExtractorClient interface {
	// Parses each file in the given set of repositories. Results are streamed
	// rather than returned at once (e.g. in a response message with a repeated field),
	// as each repository in a batch may contain a huge number of files.
	ParseEveryFileToUast(ctx context.Context, in *RepositoriesBatch, opts ...grpc.CallOption) (UastExtractor_ParseEveryFileToUastClient, error)
}

type uastExtractorClient struct {
	cc *grpc.ClientConn
}

func NewUastExtractorClient(cc *grpc.ClientConn) UastExtractorClient {
	return &uastExtractorClient{cc}
}

func (c *uastExtractorClient) ParseEveryFileToUast(ctx context.Context, in *RepositoriesBatch, opts ...grpc.CallOption) (UastExtractor_ParseEveryFileToUastClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_UastExtractor_serviceDesc.Streams[0], c.cc, "/org.bzz.extractor.protobuf.UastExtractor/ParseEveryFileToUast", opts...)
	if err != nil {
		return nil, err
	}
	x := &uastExtractorParseEveryFileToUastClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type UastExtractor_ParseEveryFileToUastClient interface {
	Recv() (*FileUast, error)
	grpc.ClientStream
}

type uastExtractorParseEveryFileToUastClient struct {
	grpc.ClientStream
}

func (x *uastExtractorParseEveryFileToUastClient) Recv() (*FileUast, error) {
	m := new(FileUast)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for UastExtractor service

type UastExtractorServer interface {
	// Parses each file in the given set of repositories. Results are streamed
	// rather than returned at once (e.g. in a response message with a repeated field),
	// as each repository in a batch may contain a huge number of files.
	ParseEveryFileToUast(*RepositoriesBatch, UastExtractor_ParseEveryFileToUastServer) error
}

func RegisterUastExtractorServer(s *grpc.Server, srv UastExtractorServer) {
	s.RegisterService(&_UastExtractor_serviceDesc, srv)
}

func _UastExtractor_ParseEveryFileToUast_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RepositoriesBatch)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(UastExtractorServer).ParseEveryFileToUast(m, &uastExtractorParseEveryFileToUastServer{stream})
}

type UastExtractor_ParseEveryFileToUastServer interface {
	Send(*FileUast) error
	grpc.ServerStream
}

type uastExtractorParseEveryFileToUastServer struct {
	grpc.ServerStream
}

func (x *uastExtractorParseEveryFileToUastServer) Send(m *FileUast) error {
	return x.ServerStream.SendMsg(m)
}

var _UastExtractor_serviceDesc = grpc.ServiceDesc{
	ServiceName: "org.bzz.extractor.protobuf.UastExtractor",
	HandlerType: (*UastExtractorServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ParseEveryFileToUast",
			Handler:       _UastExtractor_ParseEveryFileToUast_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "protobuf/extractor.proto",
}

func init() { proto.RegisterFile("protobuf/extractor.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 274 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0x41, 0x4b, 0xfb, 0x40,
	0x10, 0xc5, 0xff, 0xfb, 0x6f, 0x4d, 0xcd, 0xd8, 0x1e, 0x5c, 0x44, 0x96, 0xe2, 0xa1, 0x44, 0x0f,
	0xb9, 0x18, 0x45, 0x2f, 0x9e, 0x0b, 0x15, 0x7a, 0x93, 0x60, 0x2f, 0x5e, 0x64, 0x93, 0x4e, 0x9a,
	0x40, 0xe8, 0x86, 0xd9, 0x8d, 0xd8, 0x9e, 0xfc, 0x3c, 0x7e, 0x4a, 0x99, 0xad, 0xb1, 0xa0, 0xe8,
	0xed, 0xcd, 0xef, 0xbd, 0x81, 0x99, 0x07, 0xaa, 0x21, 0xe3, 0x4c, 0xd6, 0x16, 0x57, 0xf8, 0xea,
	0x48, 0xe7, 0xce, 0x50, 0xe2, 0x91, 0x1c, 0x1b, 0x5a, 0x25, 0xd9, 0x76, 0x9b, 0x7c, 0x33, 0xb2,
	0xb6, 0x88, 0xee, 0xe0, 0x38, 0xc5, 0xc6, 0xd8, 0xca, 0x19, 0xaa, 0xd0, 0x4e, 0xb5, 0xcb, 0x4b,
	0x79, 0x0e, 0x23, 0xea, 0xe0, 0xe6, 0xb9, 0x5a, 0x2a, 0x31, 0xe9, 0xc5, 0x61, 0x3a, 0xdc, 0xc3,
	0xf9, 0x32, 0x7a, 0x17, 0x70, 0x78, 0x5f, 0xd5, 0xb8, 0xd0, 0xd6, 0xc9, 0x53, 0x08, 0xd8, 0x9c,
	0x73, 0x54, 0xc4, 0x61, 0xfa, 0x39, 0x49, 0x05, 0x03, 0x56, 0x0b, 0xaa, 0xd5, 0x7f, 0x6f, 0x74,
	0xa3, 0x94, 0xd0, 0x6f, 0xb4, 0x2b, 0x55, 0xcf, 0x63, 0xaf, 0x99, 0xd5, 0x7a, 0xbd, 0x52, 0xfd,
	0x1d, 0x63, 0xcd, 0xac, 0xd5, 0xd6, 0xa9, 0x83, 0x89, 0x88, 0x87, 0xa9, 0xd7, 0xf2, 0x0c, 0x42,
	0xc2, 0x02, 0x09, 0xd7, 0x39, 0xaa, 0xc0, 0x87, 0xf7, 0x80, 0x37, 0x4a, 0x6d, 0x4b, 0x35, 0xd8,
	0x6d, 0xb0, 0xbe, 0x79, 0x13, 0x30, 0xe2, 0x43, 0x67, 0x5d, 0x03, 0xd2, 0xc0, 0xc9, 0x83, 0x26,
	0x8b, 0xb3, 0x17, 0xa4, 0x0d, 0xff, 0xf1, 0x68, 0xfc, 0x27, 0x97, 0xc9, 0xef, 0x6d, 0x25, 0x3f,
	0xaa, 0x1a, 0x5f, 0xfc, 0x15, 0xef, 0xea, 0x89, 0xfe, 0x5d, 0x8b, 0xe9, 0xd1, 0x53, 0xf8, 0x15,
	0xc9, 0x02, 0x9f, 0xb9, 0xfd, 0x08, 0x00, 0x00, 0xff, 0xff, 0x92, 0x21, 0x5b, 0xfd, 0xb5, 0x01,
	0x00, 0x00,
}
